
class AppString{
  static const String ceoIntro='Message from the Chairman';
  static const String ceoName='Mohammad Emran Pir';
  static const String ceoMsg='Government Employees although are painted as a privileged class but'
      ' the reality is very few of them in millions are enjoying sheer perks'
      ' and privileges. A very thumping majority of them are living in miserable'
      ' conditions having no access to proper education, health and housing.'
      ' Some of the state-run organizations are working in the housing sector'
      ' to facilitate the government sector employees but that is totally insufficient.World'
      ' Bank reports that around 47 % of urban households live in informal settlements'
      ' (katchi abadis) with limited access to civic infrastructure and sanitary services.'
      ' The immediate public health costs, and long-term social capital costs, of nearly'
      ' half the city living in squatter settlements, are staggering. Further, the total'
      ' national housing deficit is estimated at over 12 million units, and this gap'
      ' increases by 350,000 units every year with the incremental deficit expected'
      ' to rise to 400,000 units per annum in a few years. Among many factors that'
      ' prevent safe and secure shelter for Pakistanis is the architecture of the'
      ' existing real estate market — it is a market that actively excludes middle- and'
      ' low-income groups, and extracts great profits from those who can afford to be'
      ' fleeced.We at Government Employees Foundation has pledged to join'
      ' hands with the state to help eradicate the shortage of housing for'
      ' at least a few very important segments of the society including the '
      'public and private sector employees. We anticipate a healthy and trust-based '
      'participation of the targeted community, and pledge that we will never breach'
      ' the trust of our members.';
  static const String intro='Housing is one of the three most important basic needs of human beings.'
      ' Present day scenario paints that we as a developing country facing a virtual housing crisis.'
      ' Shortage of supply, aging housing stock, development of slums and Katchi Abadis, '
      'poor civic administration, and lack of financial resources has worsened the situation.'
      ' While rapid growth in our native population and due to the influx of ignorant aliens '
      'who a single pair are parenting dozens of children is adding fuel to fire.\n\n'

      'Pakistan ranks'' 7th amongst the most populous nations in the world while its land area is 34th largest in'
      ' the world. According to the recent census Pakistan has over 250 million people living in'
      ' it which is 50 million more than 2017 census. Its urban population has been growing by'
      ' over 2.7% per Anum and its estimated at 75.5 million. According to the 2017 census, the'
      ' total number of housing units throughout the country was 32.2 million. 63.6% of housing'
      ' was in rural areas and 36.4% in urban areas.\n\n'
      'Government Employees Foundation (GEF), Pakistan'
      ' is a non-profit organization that aims at volunteering for the Government Employees of Pakistan.'
      ' The Foundation is registered under societies registration act, 1860 since 2015. '
      'The Government Employees Foundation is a self-financed entity and does not get any'
      ' funds from any government exchequer or the private sector. Therefore, GEF does not'
      ' possess sufficient funds for the purchase of land in advance. Hence, a down payment is collected '
      'from its members at the time of the launch/announcement of housing schemes. The amount so collected'
      ' is utilized for partial payment regarding the procurement of raw land. On receipt of installments'
      ' collected from allottees, the balance amount of land is paid.The management of the foundation'
      ' has decided to launch a much affordable housing scheme in federal capital zone. After very'
      ' careful exploration has selected the area of Tarnol Interchange, M-1 motorway Islamabad.'
      ' GEF has started a membership drive for this project to offer its members an opportunity'
      ' to apply for a much-needed affordable housing scheme.';
  static const String mission='“Home for Everyone” is a punch line that Government Employees Foundation '
      'Pakistan has adopted. Government Employees Foundation undertakes to provide eligible government'
      ' employees with quality affordable housing in a secure, healthy, and decent environment. Also, '
      'working in partnership with the public and private sectors, the Foundation provides families '
      'with housing choices and opportunities.';
  static const String footerMsg='19 Valley is an accomplished state-of-the-art society, '
      'with a Community Center, Commercial Area, Health Club, Mosque, Security'
      ' cameras/surveillance along with a well-built protective boundary wall.';
  static const String welcomeMsg='Greetings from 19 Valley Society! We\'re excited to welcome you to '
      'our vibrant community. With a strong sense of togetherness, '
      'we foster connections among residents. Our lush landscapes, '
      'modern amenities, and engaging events create a thriving environment for all.'
      ' Share in our passion for a balanced lifestyle, where convenience meets tranquility.'
      ' Explore local markets, relish stunning views, and partake in enriching activities.'
      ' Join us in shaping memorable experiences and a harmonious neighborhood.'
      ' Together, we build the future amidst the beauty of 19 Valley Society.';
}